'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
type P={flap:number;gravity:number;speed:number;gap:number;spacing:number};
const classic:P={flap:7.2,gravity:.42,speed:3,gap:82,spacing:225};
const groups=[{id:'flight',no:'01',short:'飛行',title:'飛行手感',sub:'調整每次拍翅的力度與下墜速度',controls:[['flap','拍翅力度',3,12,.2,'越高：每次點擊飛得更高'],['gravity','重力',.15,1,.01,'越高：小鳥下墜得更快']]},{id:'world',no:'02',short:'速度',title:'世界速度',sub:'決定管道向左移動的節奏',controls:[['speed','移動速度',1,7,.1,'越高：反應時間越短']]},{id:'pipes',no:'03',short:'管道',title:'管道難度',sub:'調整通道大小與管道出現距離',controls:[['gap','通道高度',48,140,2,'越高：通過管道更容易'],['spacing','管道間距',140,360,5,'越高：休息時間更充裕']]}] as const;
export default function Home(){
 const cv=useRef<HTMLCanvasElement>(null),run=useRef({raf:0,last:0,y:100,v:0,pipes:[{x:620,top:70,passed:false}],score:0,time:0});
 const [p,setP]=useState<P>({flap:8.4,gravity:.48,speed:3.4,gap:96,spacing:245}),pr=useRef(p);const [tab,setTab]=useState('flight'),[status,setStatus]=useState<'ready'|'playing'|'paused'|'over'>('ready'),[mode,setMode]=useState<'custom'|'classic'>('custom'),[result,setResult]=useState<number|null>(null),[sound,setSound]=useState(true),[m,setM]=useState({score:0,time:0,best:0});const group=groups.find(x=>x.id===tab)!,feel=useMemo(()=>p.flap/p.gravity,[p]);
 useEffect(()=>{pr.current=mode==='classic'?classic:p},[p,mode]);
 const reset=useCallback((play=false)=>{cancelAnimationFrame(run.current.raf);run.current={raf:0,last:0,y:100,v:0,pipes:[{x:620,top:58+Math.random()*58,passed:false}],score:0,time:0};setM(x=>({score:0,time:0,best:x.best}));setStatus(play?'playing':'ready')},[]);
 const flap=useCallback(()=>{if(status==='ready'||status==='over'){reset(true);setTimeout(()=>run.current.v=-pr.current.flap)}else if(status==='playing')run.current.v=-pr.current.flap},[status,reset]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();flap()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[flap]);
 useEffect(()=>{const c=cv.current?.getContext('2d');if(!c)return;const draw=()=>{const r=run.current,q=pr.current;c.fillStyle='#dcecef';c.fillRect(0,0,600,220);c.fillStyle='#fff8';for(let x=70;x<600;x+=180){c.fillRect(x,35,52,12);c.fillRect(x+12,24,25,12)}c.fillStyle='#c8d6a0';c.fillRect(0,196,600,24);c.fillStyle='#8c9f62';c.fillRect(0,190,600,7);for(const pipe of r.pipes){const bottom=pipe.top+q.gap;c.fillStyle='#6f9473';c.fillRect(pipe.x,0,52,pipe.top);c.fillRect(pipe.x,bottom,52,190-bottom);c.fillStyle='#496b55';c.fillRect(pipe.x-5,pipe.top-15,62,15);c.fillRect(pipe.x-5,bottom,62,15);c.fillStyle='#a8c78e';c.fillRect(pipe.x+7,0,8,pipe.top-15);c.fillRect(pipe.x+7,bottom+15,8,175-bottom)}const x=88,y=r.y;c.fillStyle='#f0bc47';c.fillRect(x-14,y-12,25,24);c.fillStyle='#fff';c.fillRect(x+4,y-9,10,10);c.fillStyle='#26342f';c.fillRect(x+10,y-6,3,3);c.fillStyle='#df7e3f';c.fillRect(x+12,y,13,6);c.fillStyle='#d69a36';c.fillRect(x-22,y-3,10,8);c.fillStyle='#26342f';c.font='700 22px monospace';c.textAlign='center';c.fillText(String(r.score),300,30);if(status!=='playing'){c.fillStyle='#f8f6e9dc';c.fillRect(0,0,600,220);c.fillStyle='#26342f';c.font='800 16px monospace';c.fillText(status==='over'?'GAME OVER':status==='paused'?'PAUSED':'點一下，開始飛行',300,103);c.font='12px Arial';c.fillText(status==='over'?'再試一次，微調你的參數':'SPACE / ↑ / 點擊畫面',300,126)}};draw();if(status!=='playing')return;const tick=(t:number)=>{const r=run.current,q=pr.current,dt=Math.min(32,t-(r.last||t-16))/16.67;r.last=t;r.time+=dt/60;r.v+=q.gravity*dt;r.y+=r.v*dt;for(const pipe of r.pipes){pipe.x-=q.speed*dt;if(!pipe.passed&&pipe.x+52<88){pipe.passed=true;r.score++}}const last=r.pipes[r.pipes.length-1];if(last.x<600-q.spacing)r.pipes.push({x:630,top:42+Math.random()*(135-q.gap/2),passed:false});r.pipes=r.pipes.filter(x=>x.x>-70);const hit=r.y<10||r.y>183||r.pipes.some(pipe=>102>pipe.x&&74<pipe.x+52&&(r.y-12<pipe.top||r.y+12>pipe.top+q.gap));setM(x=>({score:r.score,time:r.time,best:Math.max(x.best,r.score)}));if(hit){setStatus('over');return}draw();r.raf=requestAnimationFrame(tick)};run.current.raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(run.current.raf)},[status,m.score]);
 const grade=()=>{const ranges:P={flap:9,gravity:.85,speed:6,gap:92,spacing:220};const d=(Object.keys(classic) as (keyof P)[]).reduce((s,k)=>s+Math.abs(p[k]-classic[k])/ranges[k],0)/5;setResult(Math.max(0,Math.round(100-d*240)))};const randomize=()=>setP({flap:5+Math.random()*5,gravity:.25+Math.random()*.45,speed:2+Math.random()*3,gap:60+Math.round(Math.random()*55),spacing:170+Math.round(Math.random()*140)});
 return <main><header><div className="brand"><b>●</b><span><strong>FLAP LAB</strong><small>GAME FEEL TUNING</small></span></div><div className="round">ROUND 01 <button onClick={()=>setSound(!sound)}>♪ {sound?'ON':'OFF'}</button></div></header><div className="layout"><section className="game"><div className="gamein"><div className="title"><span><em>PLAYTEST</em><h1>飛翔小鳥測試場</h1></span>{result===null?<i>MY BUILD</i>:<div className="modes"><button className={mode==='custom'?'on':''} onClick={()=>{setMode('custom');reset()}}>我的設定</button><button className={mode==='classic'?'on':''} onClick={()=>{setMode('classic');reset()}}>經典參數</button></div>}</div><div className="frame"><label>{mode==='classic'?'CLASSIC':'MY BUILD'}</label><canvas ref={cv} width="600" height="220" onPointerDown={flap} aria-label="飛翔小鳥遊戲區"/></div><div className="play"><button className="jump" onClick={flap}>{status==='ready'?'開始飛行':status==='over'?'重新挑戰':'拍翅'} <kbd>SPACE</kbd></button><button onClick={()=>setStatus(status==='playing'?'paused':'playing')}>{status==='paused'?'▶ 繼續':'Ⅱ 暫停'}</button><button onClick={()=>reset()}>↻ 重設</button></div><div className="metrics">{[['分數',String(m.score).padStart(2,'0')],['最佳',String(m.best).padStart(2,'0')],['飛行時間',m.time.toFixed(1)+'s'],['飛行手感',feel.toFixed(1)]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></section><aside><div className="scroll">{result===null?<div className="intro"><span><em>TUNE</em><h2>調整遊戲參數</h2></span><button onClick={randomize}>↻ 新題</button></div>:<div className="result"><span><small>經典相似度</small><b>{result}<i>/100</i></b></span><div><h3>{result>85?'就是這個手感！':result>65?'很接近了':'還能再調順一點'}</h3><p>切換經典參數試飛，再回來找到你的最佳手感。</p><label><i style={{width:result+'%'}}/></label></div></div>}<nav>{groups.map(s=><button key={s.id} className={tab===s.id?'on':''} onClick={()=>setTab(s.id)}><small>{s.no}</small>{s.short}</button>)}</nav><article className="panel"><div className="paneltitle"><b>{group.no}</b><span><h2>{group.title}</h2><p>{group.sub}</p></span></div>{group.controls.map(c=>{const [key,label,min,max,step,effect]=c,val=p[key];return <section className="param" key={key}><div><strong>{label}</strong><output>{val.toFixed(step<.1?2:step<1?1:0)}</output></div><input type="range" min={min} max={max} step={step} value={val} style={{'--progress':(val-min)/(max-min)*100+'%'} as React.CSSProperties} onChange={e=>{setMode('custom');setP({...p,[key]:+e.target.value})}}/><small><i>{min}</i><i>{max}</i></small><p>{effect}</p>{result!==null&&<label className="answer">經典答案：<b>{classic[key]}</b><button onClick={()=>setP({...p,[key]:classic[key]})}>套用答案</button></label>}</section>})}</article><footer><span>{result===null?'提交後解鎖經典參數':'經典參數已解鎖'}</span><button onClick={grade}>{result===null?'提交並評分':'重新評分'} <b>→</b></button></footer></div></aside></div></main>}
